### ISSUE TITLE
Neat hack, but this is also theft.

### ISSUE THREAD

**Issue by CameronBanga** [apoorvparijat/dominos.js#1]
Come on man, don't be an asshole.

**Comment by pragunbhutani** [comment]
+1

**Comment by CameronBanga** [comment]
I'm really not butt hurt at all, I couldn't give a shit personally about you stealing from Dominos.

Although it is awesome that you found a post I wrote 4 years ago, I would also remind you that I never condoned piracy in any manner, be it from individual devs or large corporations. My statement was just a reminder that not all piracy hurt large faceless corporations.

Again, to stress, I'm not butt hurt. But this is theft plain and simple. Feel free to use it, but was more of a quick reminder that if there are negative consequences, you're clearly stealing from them, so don't be upset if there are repercussions. 

Obviously from your defensiveness here, I must have struck some sort of sour note. Calling you an asshole has nothing to do with piracy of my own software four years ago. It has to do with the fact that this is black hat, and you know it. You're obviously a brilliant guy, and I'm sure this works as you've advertised. So why not do the right thing, report it to Domino's tech team, and move on.
